In [1]:
import pandas as pd
import numpy as np
import math
import json

import sys
sys.path.append('..')
import src.month_week_plan.solve_by_udf  as udf_func


In [2]:
# 获取基础数据

base_data = pd.read_csv('../data/base_data.csv',nrows=10)
base_data.head(2)

Unnamed: 0          dt user_log_acct  my_hash_code  month_hash  \
0           0  2022-06-01         -Nope            50           4   
1           1  2022-06-01          -sam            68          57   

  user_life_cycle_type_1st  model_a_1st  model_b_1st goal_group_1st  \
0                      成熟期            5            5           都市中产   
1                      成熟期            5            3           小镇家庭   

   annual_clv_1st  ... com_base_cnt  free_base_cnt no_ctrl_base_cnt  \
0               5  ...     2.535171       5.856637        11.683798   
1               5  ...     2.546215       2.906346         7.363674   

   strong_ctrl_base_cnt  normal_ctrl_base_cnt  com_cnt_rate  free_cnt_rate  \
0              0.196020              4.002024      0.992779       1.159169   
1              0.065493              3.937758      1.281925       1.314577   

  strong_cnt_rate  normal_cnt_rate  nocontrol_cnt_rate  
0        2.326014         0.942478            1.626886  
1        2.147202         1.169328            2.069599  

[2 rows x 87 columns]

In [3]:
## 保量逻辑校验
pra1 = list(base_data.columns.values).index('com_login_cnt_last_month')
pra2 = list(base_data.columns.values).index('free_login_cnt_last_month')
pra3 = list(base_data.columns.values).index('strong_ctrl_login_cnt_last_month')
pra4 = list(base_data.columns.values).index('strong_ctrl_login_cnt_last_month')
pra5 = list(base_data.columns.values).index('no_ctrl_login_cnt_last_month')

basic_result_list = []
for indexs in base_data.index:
    print(base_data.loc[indexs].values[pra1:pra5])
    basic_result = udf_func.BasicGuarantee(base_data.loc[indexs].values[pra1],
                            base_data.loc[indexs].values[pra2],
                            base_data.loc[indexs].values[pra3],
                            base_data.loc[indexs].values[pra4],
                            base_data.loc[indexs].values[pra5])
    print(basic_result)
    basic_result_list.append(basic_result)

base_data['basic_result'] = basic_result_list


[0 0 0 0]
{'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
{'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
[0 9 0 4]
{'com': 0, 'free': 9, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 20}
{'com': 0, 'free': 9, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 20}
[0 0 0 0]
{'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
{'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
[0 2 0 0]
{'com': 0, 'free': 2, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
{'com': 0, 'free': 2, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
[0 0 0 3]
{'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 3}
{'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 3}
[0 0 0 0]
{'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
{'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
[0 0 2 0]
{'com': 0, 'free': 0, 'strong_ctrl': 2, 'normal_ctrl': 2, 'no_ct

In [4]:
## 业务补量逻辑
par1 = list(base_data.columns.values).index('basic_result')
par2  = list(base_data.columns.values).index('priority_type')
year_clv_threshold = 2
par4  = list(base_data.columns.values).index('gmv_year')
par5 = list(base_data.columns.values).index('clv_pred_1m')
month_clv_threshold = 50
par7  = list(base_data.columns.values).index('com_login_cnt_last_month')
par8 = list(base_data.columns.values).index('free_login_cnt_last_month')
par9 = list(base_data.columns.values).index('strong_ctrl_login_cnt_last_month')
par10  = list(base_data.columns.values).index('normal_ctrl_login_cnt_last_month')
par11 = list(base_data.columns.values).index('no_ctrl_login_cnt_last_month')
par12 = list(base_data.columns.values).index('my_hash_code')
par13 = list(base_data.columns.values).index('month_hash')

businessrule_plan_list  = []
businessrule_no_allocation_channel_list = []
channel_businessrule_max_list =[]
channel_businessrule_max_add_list = []

for indexs in base_data.index:
    # print(base_data.loc[indexs].values[par1:par13])
    businessrule_plan, businessrule_no_allocation_channel, channel_businessrule_max, channel_businessrule_max_add = udf_func.BusinessRuleSupplement(base_data.loc[indexs].values[par1],
                                                                                                                                                    base_data.loc[indexs].values[par2],
                                                                                                                                                    year_clv_threshold,
                                                                                                                                                    base_data.loc[indexs].values[par4],
                                                                                                                                                    base_data.loc[indexs].values[par5],
                                                                                                                                                    month_clv_threshold,
                                                                                                                                                    base_data.loc[indexs].values[par7],
                                                                                                                                                    base_data.loc[indexs].values[par8],
                                                                                                                                                    base_data.loc[indexs].values[par9],
                                                                                                                                                    base_data.loc[indexs].values[par10],
                                                                                                                                                    base_data.loc[indexs].values[par11],
                                                                                                                                                    base_data.loc[indexs].values[par12],
                                                                                                                                                    base_data.loc[indexs].values[par13])
    businessrule_plan_list.append(businessrule_plan)
    businessrule_no_allocation_channel_list.append(businessrule_no_allocation_channel)
    channel_businessrule_max_list.append(channel_businessrule_max)
    channel_businessrule_max_add_list.append(channel_businessrule_max_add)

base_data['businessrule_plan'] = businessrule_plan_list
base_data['businessrule_no_allocation_channel'] = businessrule_no_allocation_channel_list
base_data['channel_businessrule_max'] = channel_businessrule_max_list
base_data['channel_businessrule_max_add'] = channel_businessrule_max_add_list

basic_result {'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
businessrule_plan        {'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
businessrule_plan['com'] 0
user_label == 'A1'
channel_days 0.0
my_hash_code > hash_precent 
businessrule_plan:                   {'com': 0, 'free': 1, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
businessrule_no_allocation_channel:  ['normal_ctrl']
channel_businessrule_max:            {'com': 0.0}
channel_businessrule_max_add:        {'com': 0, 'free': 1, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
basic_result {'com': 0, 'free': 9, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 20}
businessrule_plan        {'com': 0, 'free': 9, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 20}
businessrule_plan['com'] 0
user_label == 'A2'
clv > month_clv_threshold clv>50, 保量+阶跃
businessrule_plan['normal_ctrl'] == 0 businessrule_plan['normal_ctrl'] +=1
businessrule_plan:                   {'com': 0, 'free': 9, '

In [5]:
## 渠道上下限测试
columns_list = list(base_data.columns.values)
i_part_dt = columns_list.index('dt')
i_priority_type  = columns_list.index('priority_type')
i_my_hash_code = columns_list.index('my_hash_code')
i_channel_businessrule_max_add = columns_list.index('channel_businessrule_max_add')
i_channel_businessrule_max = columns_list.index('channel_businessrule_max')
i_com_max_login_count = columns_list.index('com_max_login_count')
i_free_max_login_count = columns_list.index('free_max_login_count')
i_strong_ctrl_max_login_count = columns_list.index('strong_ctrl_max_login_count')
i_normal_ctrl_max_login_count  = columns_list.index('normal_ctrl_max_login_count')
i_no_ctrl_max_login_count  = columns_list.index('no_ctrl_max_login_count')
i_com_login_cnt_last_month = columns_list.index('com_login_cnt_last_month')
i_free_login_cnt_last_month  = columns_list.index('free_login_cnt_last_month')
i_strong_ctrl_login_cnt_last_month = columns_list.index('strong_ctrl_login_cnt_last_month')
i_normal_ctrl_login_cnt_last_month = columns_list.index('normal_ctrl_login_cnt_last_month')
i_no_ctrl_login_cnt_last_month  = columns_list.index('no_ctrl_login_cnt_last_month')
i_is_acce_by_com = columns_list.index('is_acce_by_com')
i_is_acce_by_free = columns_list.index('is_acce_by_free')
i_is_acce_by_strong_ctrl = columns_list.index('is_acce_by_strong_ctrl')
i_is_acce_by_normal_ctrl = columns_list.index('is_acce_by_normal_ctrl') 
i_is_acce_by_no_ctrl = columns_list.index('is_acce_by_no_ctrl')
month_clv_threshold = 50
channel_max_adjust = 1.0
channel_preference = [1.0]
i_com_login_cnt_mtd = columns_list.index('com_login_cnt_mtd')
i_free_login_cnt_mtd = columns_list.index('free_login_cnt_mtd')
i_strong_ctrl_login_cnt_mtd = columns_list.index('strong_ctrl_login_cnt_mtd')
i_normal_ctrl_login_cnt_mtd = columns_list.index('normal_ctrl_login_cnt_mtd')
i_no_ctrl_login_cnt_mtd = columns_list.index('no_ctrl_login_cnt_mtd')
between_channel_adjust = 0

channel_max_login_days_list = []
for indexs in base_data.index:
    # print(base_data.loc[indexs].values[par1:par13])
    print("-"*10)
    channel_max_login_days = udf_func.get_user_channel_max_func(base_data.loc[indexs].values[i_part_dt],
                                                                    base_data.loc[indexs].values[i_priority_type],
                                                                    base_data.loc[indexs].values[i_my_hash_code],
                                                                    base_data.loc[indexs].values[i_channel_businessrule_max_add],
                                                                    base_data.loc[indexs].values[i_channel_businessrule_max],
                                                                    base_data.loc[indexs].values[i_com_max_login_count],
                                                                    base_data.loc[indexs].values[i_free_max_login_count],
                                                                    base_data.loc[indexs].values[i_strong_ctrl_max_login_count],
                                                                    base_data.loc[indexs].values[i_normal_ctrl_max_login_count],
                                                                    base_data.loc[indexs].values[i_no_ctrl_max_login_count],
                                                                    base_data.loc[indexs].values[i_com_login_cnt_last_month],
                                                                    base_data.loc[indexs].values[i_free_login_cnt_last_month],
                                                                    base_data.loc[indexs].values[i_strong_ctrl_login_cnt_last_month],
                                                                    base_data.loc[indexs].values[i_normal_ctrl_login_cnt_last_month],
                                                                    base_data.loc[indexs].values[i_no_ctrl_login_cnt_last_month],
                                                                    base_data.loc[indexs].values[i_is_acce_by_com],
                                                                    base_data.loc[indexs].values[i_is_acce_by_free],
                                                                    base_data.loc[indexs].values[i_is_acce_by_strong_ctrl],
                                                                    base_data.loc[indexs].values[i_is_acce_by_normal_ctrl],
                                                                    base_data.loc[indexs].values[i_is_acce_by_no_ctrl],
                                                                    month_clv_threshold,
                                                                    channel_max_adjust,
                                                                    channel_preference,
                                                                    base_data.loc[indexs].values[i_com_login_cnt_mtd],
                                                                    base_data.loc[indexs].values[i_free_login_cnt_mtd],
                                                                    base_data.loc[indexs].values[i_strong_ctrl_login_cnt_mtd],
                                                                    base_data.loc[indexs].values[i_normal_ctrl_login_cnt_mtd],
                                                                    base_data.loc[indexs].values[i_no_ctrl_login_cnt_mtd],
                                                                    between_channel_adjust)
    channel_max_login_days_list.append(channel_max_login_days)
    # print("-"*10)
base_data['channel_max_login_days'] = channel_max_login_days_list


----------
channel_businessrule_max_add {'com': 0, 'free': 1, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
channel_businessrule_max     {'com': 0.0}
1 {'com': 1, 'free': 1, 'strong_ctrl': 1, 'normal_ctrl': 1, 'no_ctrl': 1}
channel_days 0.0
com 1.2*上月 < 上限 
channel_max_login_days['com'] 0.0
channel_days 0.0
channel_days 0.0
channel_days 0.0
2 {'com': 0.0, 'free': 0.0, 'strong_ctrl': 0.0, 'normal_ctrl': 0.0, 'no_ctrl': 0}
channel_max_login_days {'com': 0.0, 'free': 1.0, 'strong_ctrl': 0.0, 'normal_ctrl': 0.0, 'no_ctrl': 0}
----------
channel_businessrule_max_add {'com': 0, 'free': 0, 'strong_ctrl': 0, 'normal_ctrl': 1, 'no_ctrl': 0}
channel_businessrule_max     {}
1 {'com': 1, 'free': 1, 'strong_ctrl': 1, 'normal_ctrl': 1, 'no_ctrl': 1}
channel_days 0.0
com 1.2*上月 < 上限 
channel_max_login_days['com'] 0.0
 my_hash_code <= adjust_day_hash_add channel_days += 1
channel_days 11.0
channel_days 0.0
 my_hash_code <= adjust_day_hash_add channel_days += 1
channel_days 5.0
2 {'com': 0.0, 'free

In [6]:
## 目标值和渠道成本测试样例
i_part_dt = columns_list.index('dt')
i_lower_lift_login_cnt = columns_list.index('lower_lift_login_cnt')
i_natural_pred_login_cnt_rest  = columns_list.index('natural_pred_login_cnt_rest')
i_login_cnt_mtd = columns_list.index('login_cnt_mtd')
i_no_ctrl_login_cnt_last_month  = columns_list.index('no_ctrl_login_cnt_last_month')
i_no_ctrl_login_cnt_mtd = columns_list.index('no_ctrl_login_cnt_mtd')

target_login_days_list = []
for indexs in base_data.index:
    target_login_days = udf_func.get_target_allocation_login(base_data.loc[indexs].values[i_part_dt],
                                                         base_data.loc[indexs].values[i_lower_lift_login_cnt],
                                                         base_data.loc[indexs].values[i_natural_pred_login_cnt_rest],
                                                         base_data.loc[indexs].values[i_login_cnt_mtd],
                                                         base_data.loc[indexs].values[i_no_ctrl_login_cnt_last_month] - base_data.loc[indexs].values[i_no_ctrl_login_cnt_mtd])
    target_login_days_list.append(target_login_days)
base_data['target_login_days'] = target_login_days_list
# 目标值


# 渠道成本
channel_type = ['com','free', 'strong_ctrl', 'normal_ctrl', 'no_ctrl']
i_com_login_cost = columns_list.index('com_login_cost')
i_free_login_cost = columns_list.index('free_login_cost')
i_strong_ctrl_login_cost = columns_list.index('strong_ctrl_login_cost')
i_normal_login_cost = columns_list.index('normal_login_cost')
i_no_ctrl_login_cost = columns_list.index('no_ctrl_login_cost')
i_com_login_cnt_per_dau = columns_list.index('com_login_cnt_per_dau')
i_free_login_cnt_per_dau = columns_list.index('free_login_cnt_per_dau')
i_strong_ctrl_login_cnt_per_dau = columns_list.index('strong_ctrl_login_cnt_per_dau')
i_normal_ctrl_login_cnt_per_dau = columns_list.index('normal_ctrl_login_cnt_per_dau')
i_no_ctrl_login_cnt_per_dau = columns_list.index('no_ctrl_login_cnt_per_dau')
i_com_quality_coeff = columns_list.index('com_quality_coeff')
i_free_quality_coeff = columns_list.index('free_quality_coeff')
i_strong_ctrl_quality_coeff = columns_list.index('strong_ctrl_quality_coeff')
i_normal_ctrl_quality_coeff = columns_list.index('normal_ctrl_quality_coeff')
i_no_ctrl_quality_coeff = columns_list.index('no_ctrl_quality_coeff')

channel_login_costs_list = []
for indexs in base_data.index:
    channel_login_costs = udf_func.get_channel_login_costs(channel_type,
                                                        base_data.loc[indexs].values[i_com_login_cost],
                                                        base_data.loc[indexs].values[i_free_login_cost],
                                                        base_data.loc[indexs].values[i_strong_ctrl_login_cost],
                                                        base_data.loc[indexs].values[i_normal_login_cost],
                                                        base_data.loc[indexs].values[i_no_ctrl_login_cost],
                                                        base_data.loc[indexs].values[i_com_login_cnt_per_dau],
                                                        base_data.loc[indexs].values[i_free_login_cnt_per_dau],
                                                        base_data.loc[indexs].values[i_strong_ctrl_login_cnt_per_dau],
                                                        base_data.loc[indexs].values[i_normal_ctrl_login_cnt_per_dau],
                                                        base_data.loc[indexs].values[i_no_ctrl_login_cnt_per_dau],
                                                        base_data.loc[indexs].values[i_com_quality_coeff],
                                                        base_data.loc[indexs].values[i_free_quality_coeff],
                                                        base_data.loc[indexs].values[i_strong_ctrl_quality_coeff],
                                                        base_data.loc[indexs].values[i_normal_ctrl_quality_coeff],
                                                        base_data.loc[indexs].values[i_no_ctrl_quality_coeff])
    channel_login_costs_list.append(channel_login_costs)
        
base_data['channel_login_costs'] = channel_login_costs_list

In [7]:
# 测试贪心算法
columns_list = list(base_data.columns.values)
i_channel_login_costs = columns_list.index('channel_login_costs')
i_target_login_days = columns_list.index('target_login_days')
i_businessrule_no_allocation_channel = columns_list.index('businessrule_no_allocation_channel')
i_businessrule_plan = columns_list.index('businessrule_plan')
i_channel_max_login_days = columns_list.index('channel_max_login_days')

greedy_result_list = []
for indexs in base_data.index:
    print("-"*20)
    greedy_result = udf_func.GreedySolver(base_data.loc[indexs].values[i_target_login_days],
                                        base_data.loc[indexs].values[i_businessrule_no_allocation_channel],
                                        base_data.loc[indexs].values[i_businessrule_plan],
                                        base_data.loc[indexs].values[i_channel_max_login_days],
                                        base_data.loc[indexs].values[i_channel_login_costs])
    greedy_result_list.append(channel_login_costs)
        
base_data['greedy_result'] = greedy_result_list

--------------------
target_login_days                 : 35
businessrule_no_allocation_channel: ['normal_ctrl']
businessrule_result               : {'com': 0, 'free': 1, 'strong_ctrl': 0, 'normal_ctrl': 0, 'no_ctrl': 0}
channel_max_login_days            : {'com': 0.0, 'free': 1.0, 'strong_ctrl': 0.0, 'normal_ctrl': 0.0, 'no_ctrl': 0}
channel_login_costs               : {'com': -18.114666354016535, 'free': 0.0, 'strong_ctrl': 0.12350513876550206, 'normal_ctrl': 5.740355949744533, 'no_ctrl': 4.971470124964464}
target_login_days >0: greedy solver
待分配的渠道: com
待分配的次数 = target_login_days - businessrule_result[index]:
35 = 35 - 0
渠道上限修正为 渠道上限 - 已分配次数
0 = 0 - 0
used_day = min(channel_max_day, should_target_login_cnt)
0 = min(0 , 35)
target_login_days: 35
待分配的渠道: free
待分配的次数 = target_login_days - businessrule_result[index]:
34 = 35 - 1
渠道上限修正为 渠道上限 - 已分配次数
0 = 1 - 1
used_day = min(channel_max_day, should_target_login_cnt)
0 = min(0 , 34)
target_login_days: 35
待分配的渠道: strong_ctrl
待分配的次数 = target